In [9]:
import  nevis
import numpy as np 
import matplotlib.pyplot as plt
h = nevis.gb()

label = np.load('../res/label.npy')
maxima = np.load('../res/maxima.npy')

In [10]:

# Get the dimensions of the label array
rows, cols = label.shape


In [11]:
def is_boundary_of_boa(i, j):
    """
    Check if the given index (i, j) is on the boundary or has a neighboring cell
    with a different label value.

    Parameters:
    label (np.ndarray): 2D numpy array with shape (26000, 14000).
    i (int): Row index of the label array.
    j (int): Column index of the label array.

    Returns:
    bool: True if the index is on the boundary or has a neighbor with a different label value.
    """
    
    # Check if (i, j) is on the boundary of the array
    if i == 0 or i == rows - 1 or j == 0 or j == cols - 1:
        return True
    
    # Get the value of the current cell
    current_value = label[i, j]
    
    # Check all 8 neighbors to see if any has a different value
    for di in [-1, 0, 1]:
        for dj in [-1, 0, 1]:
            # Skip the center cell itself
            if di == 0 and dj == 0:
                continue
            
            # Calculate neighbor coordinates
            ni, nj = i + di, j + dj
            
            # Check if the neighbor is within bounds and has a different value
            if 0 <= ni < rows and 0 <= nj < cols:
                if label[ni, nj] != current_value:
                    return True
    
    # If no neighbors are different and it's not on the boundary, return False
    return False


In [12]:
from tqdm import tqdm

In [14]:
height, index = 0, None
# We want to find the max height difference between 
# a point on the boundary of a boa and the optimum
# and record the index of this optimum
for i in tqdm(range(rows)):
    for j in range(cols):
        if not is_boundary_of_boa(i, j):
            continue
        mi, mj = maxima[label[i, j]]
        current_height = abs(h[i, j] - h[mi, mj])
        if current_height > height:
            height = current_height
            index = label[i, j]

  0%|          | 0/26000 [00:00<?, ?it/s]

100%|██████████| 26000/26000 [25:06<00:00, 17.26it/s] 


In [21]:
index

np.int32(1)

In [16]:
height

np.float32(1319.2001)

In [18]:
mi, mj = maxima[index]

In [19]:
mi, mj

(np.int32(15424), np.int32(4330))

In [20]:
h[mi, mj]

np.float32(1339.4)

In [26]:
n = 4

print(h[mi-n:mi+n+1, mj-n:mj+n+1])

[[1230.2 1228.4 1240.4 1241.4 1249.3 1251.3 1241.5 1230.2 1227.9]
 [1266.1 1269.4 1276.1 1278.7 1284.5 1287.5 1280.1 1268.2 1261.7]
 [1300.1 1301.  1306.7 1308.7 1312.6 1316.4 1314.  1305.  1293.6]
 [1315.6 1322.9 1325.6 1328.8 1333.  1338.9 1337.2 1333.9 1322.7]
 [1318.6 1327.3 1333.6 1338.4 1339.4 1333.3 1343.1 1342.1 1340.9]
 [1320.8 1330.2 1336.6 1312.7 1331.9 1255.8 1339.6 1345.3 1343.8]
 [1301.7 1327.8 1337.6 1308.6 1250.  1203.9 1222.5 1299.1 1327.7]
 [1219.1 1250.5 1302.8 1288.6 1219.2 1172.1 1183.  1227.9 1281. ]
 [1174.9 1201.6 1239.3 1262.5 1199.1 1126.  1118.2 1172.4 1190.9]]
