In [25]:
import basin
import numpy as np

arrows = [
    '↓',
    '↘',
    '→',
    '↗',
    '↑',
    '↖',
    '←',
    '↙',
    "@",  # (ab)using index -1 here
]


def run_algorithm(h):
    # print("The input height array:")
    # print(h)

    # calculate the list of maxima and the steepest neighbour for each point
    maxima, sn = basin.find_maxima(h)
    print("The coordinates of the local maxima:")
    print(maxima)
    print("The steepest neighbour of each point:")
    # print(sn)

    # print("which can be drawn as:")
    for x in sn:
        for y in x:
            print(arrows[y], end=" ")
        print()

    label, path_sum = basin.find_basins(h, sn, maxima)
    print("The b.o.a. of each point:")
    print(label)

    # print("The sum of all paths for each b.o.a.:")
    # print(path_sum)

    print()

In [26]:

a = np.array([
    [2, 2, 2, 2, 4, 2, 2, 2, 2],
    [2, 2, 2, 2, 3, 2, 2, 2, 2],
    [2, 2, 2, 3, 3, 3, 2, 2, 2],
    [2, 3, 3, 3, 3, 3, 3, 3, 2],
    [2, 2, 2, 3, 3, 3, 2, 2, 2],
    [2, 2, 2, 2, 3, 2, 2, 2, 2],
    [2, 2, 2, 2, 4, 2, 2, 2, 2],
])

run_algorithm(a)



The coordinates of the local maxima:Progress of finding local max: 1 / 7
Progress of finding local max: 7 / 7
Current iteration of expanding local max: 1
Current iteration of expanding local max: 2
Current iteration of expanding local max: 3
Current iteration of expanding local max: 4
Now doing BFS to connect flat local maxima... 

[[0 4]
 [6 4]]
The steepest neighbour of each point:
↓ ↘ ↘ → @ ← ← ↙ ↓ 
↓ ↓ ↘ ↗ ↑ ↖ ↙ ↓ ↓ 
↘ ↓ ↓ ↗ ↑ ↖ ↓ ↓ ↙ 
→ → ↘ ↓ ↓ ↓ ↖ ← ← 
↗ ↑ → ↘ ↓ ↙ ↑ ↑ ↖ 
↗ ↑ ↗ ↘ ↓ ↙ ↖ ↗ ↑ 
↗ ↗ → → @ ← ↖ ↖ ↑ 
The b.o.a. of each point:
[[1 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0]
 [1 1 1 1 1 1 0 0 0]
 [1 1 1 1 1 1 0 0 0]
 [1 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1 0]]

Progress of labelling b.o.a.: 1 / 7
Progress of labelling b.o.a.: 7 / 7


In [27]:
run_algorithm(np.array([
    [4, 2, 2, 2, 2, 4],
    [2, 2, 2, 2, 2, 2],
    [2, 2, 2, 2, 2, 2],
    [2, 2, 2, 2, 2, 2],
    [10, 2, 2, 2, 2, 4],
]))


The coordinates of the local maxima:
[[4 0]
 [0 0]
 [0 5]
 [4 5]]
The steepest neighbour of each point:
@ ← ← ↘ → @ 
↑ ↖ ↖ → ↗ ↑ 
↓ ↓ ↙ ↘ ↓ ↓ 
↓ ↙ ← ↘ ↘ ↓ 
@ ← ↖ → → @ 
The b.o.a. of each point:
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [0 0 0 3 3 3]
 [0 0 0 3 3 3]
 [0 0 0 3 3 3]]

Progress of finding local max: 1 / 5
Progress of finding local max: 5 / 5
Current iteration of expanding local max: 1
Current iteration of expanding local max: 2
Now doing BFS to connect flat local maxima... 
Progress of labelling b.o.a.: 1 / 5
Progress of labelling b.o.a.: 5 / 5


In [28]:

run_algorithm(np.array([
    [4, 2, 2, 2, 2, 4],
    [2, 2, 2, 2, 2, 2],
    [2, 2, 2, 3, 3, 3],
    [2, 2, 2, 2, 2, 2],
    [5, 2, 2, 2, 2, 4],
]))



The coordinates of the local maxima:
[[4 0]
 [0 0]
 [0 5]
 [4 5]
 [2 3]]
The steepest neighbour of each point:
@ ← ← ↘ → @ 
↑ ↖ ↘ ↓ ↗ ↑ 
↓ ↓ → @ ← ← 
↓ ↙ ↗ ↑ ↘ ↓ 
@ ← ↖ → → @ 
The b.o.a. of each point:
[[1 1 1 2 2 2]
 [1 1 4 4 2 2]
 [0 0 4 4 4 4]
 [0 0 4 4 3 3]
 [0 0 0 3 3 3]]

Progress of finding local max: 1 / 5
Progress of finding local max: 5 / 5
Current iteration of expanding local max: 1
Current iteration of expanding local max: 2
Now doing BFS to connect flat local maxima... 
Progress of labelling b.o.a.: 1 / 5
Progress of labelling b.o.a.: 5 / 5


In [29]:
run_algorithm(np.array([
    [4, 2, 2, 2, 2, 4],
    [1, 2, 2, 2, 2, 2],
    [5, 2, 2, 3, 3, 3],
    [1, 1, 2, 3, 4, 3],
    [1, 1, 2, 3, 4, 3],
]))


The coordinates of the local maxima:
[[2 0]
 [0 0]
 [0 5]
 [3 4]]
The steepest neighbour of each point:
@ ← ↙ ↘ → @ 
↓ ↙ ↘ ↓ ↗ ↑ 
@ ← → ↘ ↓ ↙ 
↑ ↖ → → @ ← 
↗ → → → ↑ ← 
The b.o.a. of each point:
[[1 1 0 2 2 2]
 [0 0 3 3 2 2]
 [0 0 3 3 3 3]
 [0 0 3 3 3 3]
 [0 3 3 3 3 3]]

Progress of finding local max: 1 / 5
Progress of finding local max: 5 / 5
Current iteration of expanding local max: 1
Current iteration of expanding local max: 2
Now doing BFS to connect flat local maxima... 
Progress of labelling b.o.a.: 1 / 5
Progress of labelling b.o.a.: 5 / 5


In [30]:
run_algorithm(np.array([
    [4, 1, 1, 1, 1, 1,],
    [1, 2, 2, 2, 2, 1,],
    [1, 2, 2, 2, 2, 1,],
    [1, 2, 2, 2, 2, 1,],
    [1, 2, 2, 2, 2, 1,],
    [4, 1, 1, 1, 1, 1,],
]))


The coordinates of the local maxima:
[[0 0]
 [5 0]]
The steepest neighbour of each point:
@ ← ↓ ↓ ↓ ↙ 
↑ ↖ ← ← ← ← 
→ ↑ ↖ ↖ ↖ ← 
→ ↓ ↙ ← ← ← 
↓ ↙ ← ↖ ↖ ← 
@ ← ↑ ↑ ↑ ↖ 
The b.o.a. of each point:
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]

Progress of finding local max: 1 / 6
Progress of finding local max: 6 / 6
Current iteration of expanding local max: 1
Current iteration of expanding local max: 2
Current iteration of expanding local max: 3
Current iteration of expanding local max: 4
Now doing BFS to connect flat local maxima... 
Progress of labelling b.o.a.: 1 / 6
Progress of labelling b.o.a.: 6 / 6


In [31]:
# this one broke the previous algorithm
run_algorithm(np.array([
    [3, 3, 3,],
    [3, 2, 2,],
    [3, 3, 3,],
]))


The coordinates of the local maxima:
[[0 0]]
The steepest neighbour of each point:
@ ← ← 
↑ ↓ ↓ 
↑ ↖ ← 
The b.o.a. of each point:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Progress of finding local max: 1 / 3
Progress of finding local max: 3 / 3
Current iteration of expanding local max: 1
Now doing BFS to connect flat local maxima... 
Progress of labelling b.o.a.: 1 / 3
Progress of labelling b.o.a.: 3 / 3


In [32]:
run_algorithm(np.array([
    [3, 3, 3, 3, 3, 3,],
    [2, 2, 2, 2, 2, 3,],
    [2, 2, 2, 2, 2, 3,],
    [2, 2, 2, 2, 2, 3,],
    [2, 2, 2, 2, 2, 3,],
    [3, 3, 3, 3, 3, 3,],
]))

The coordinates of the local maxima:
[[0 0]]
The steepest neighbour of each point:
@ ← ← ← ← ← 
↑ ↑ ↑ ↑ → ↖ 
↑ ↑ ↑ → → ↑ 
↓ ↓ ↓ ↓ → ↑ 
↓ ↓ ↓ ↓ ↓ ↑ 
→ → → → ↗ ↑ 
The b.o.a. of each point:
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

Progress of finding local max: 1 / 6
Progress of finding local max: 6 / 6
Current iteration of expanding local max: 1
Current iteration of expanding local max: 2
Now doing BFS to connect flat local maxima... 
Progress of labelling b.o.a.: 1 / 6
Progress of labelling b.o.a.: 6 / 6


In [33]:
run_algorithm(np.array([
    [0, 0, 0, 0, 0, 0, 0],
    [0, 2, 0, 3, 0, 0, 8],
    [0, 2, 2, 2, 3, 3, 3],
]))

The coordinates of the local maxima:
[[1 6]]
The steepest neighbour of each point:
↘ ↓ ↘ ↓ ↙ ↘ ↓ 
→ ↘ → ↘ ↓ → @ 
→ → ↗ → → ↗ ↑ 
The b.o.a. of each point:
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]

Progress of finding local max: 1 / 3
Progress of finding local max: 3 / 3
Current iteration of expanding local max: 1
Current iteration of expanding local max: 2
Current iteration of expanding local max: 3
Now doing BFS to connect flat local maxima... 
Progress of labelling b.o.a.: 1 / 3
Progress of labelling b.o.a.: 3 / 3


In [34]:
run_algorithm(np.array([
    [0, 0, 0, 0, 0, 0, 0],
    [0, 2, 0, 3, 0, 0, 8],
    [0, 2, 2, 2, 2, 3, 3],
]))

The coordinates of the local maxima:
[[1 6]
 [1 3]]
The steepest neighbour of each point:
↘ ↓ ↘ ↓ ↙ ↘ ↓ 
→ ↘ → @ ← → @ 
→ → ↗ ↑ → ↗ ↑ 
The b.o.a. of each point:
[[1 1 1 1 1 0 0]
 [1 1 1 1 1 0 0]
 [1 1 1 1 0 0 0]]

Progress of finding local max: 1 / 3
Progress of finding local max: 3 / 3
Current iteration of expanding local max: 1
Current iteration of expanding local max: 2
Now doing BFS to connect flat local maxima... 
Progress of labelling b.o.a.: 1 / 3
Progress of labelling b.o.a.: 3 / 3
